title: 薪火相传v1.0
description: 高性能机器人运动重定向引擎文档
url: https://example.github.io/MotionGym-Doc
back_to_top: true

theme: just-the-docs

just_the_docs:
  color_scheme: light
  heading_anchors: true
  search: true
  callouts_level: quiet

  defaults:
    - scope:
        path: ""
      values:
        layout: default
        search: true
        enable_copy_code_button: true
        has_toc: true

aux_links:
  GitHub: https://github.com/example/EmbeddedEngine

nav_enabled: true

webricks:
  headers:
    Cache-Control: "max-age=600, must-revalidate"
